"addi %[add_cnt], %[add_cnt], 1\n\t"
"addi t0, x0, 0\n\t"
"addi %[add_cnt], %[add_cnt], 1\n\t"
"addi t1, x0, 0\n\t"
"REV_LOOP:\n\t"
"addi %[others_cnt], %[others_cnt], 1\n\t"
"bge t0, %[m], REV_END\n\t"
"addi %[others_cnt], %[others_cnt], 1\n\t"
"andi t2, %[b], 1\n\t"
"addi %[others_cnt], %[others_cnt], 1\n\t"
"slli t1, t1, 1\n\t"
"addi %[others_cnt], %[others_cnt], 1\n\t"
"or t1, t1, t2\n\t"
"addi %[others_cnt], %[others_cnt], 1\n\t"
"srli %[b], %[b], 1\n\t"
"addi %[add_cnt], %[add_cnt], 1\n\t"
"addi t0, t0, 1\n\t"
"addi %[others_cnt], %[others_cnt], 1\n\t"
"beq x0, x0, REV_LOOP\n\t"
"REV_END:\n\t"
"addi %[add_cnt], %[add_cnt], 1\n\t"
"addi %[b], t1, 0\n\t"
