"addi %[add_cnt], %[add_cnt], 1\n\t"
"addi t0, %[N], 0\n\t"
"addi %[add_cnt], %[add_cnt], 1\n\t"
"addi t1, x0, 0\n\t"
"WhileLoop:\n\t"
"addi %[others_cnt], %[others_cnt], 1\n\t"
"srai t0, t0, 1\n\t"
"addi %[add_cnt], %[add_cnt], 1\n\t"
"addi t1, t1, 1\n\t"
"addi %[others_cnt], %[others_cnt], 1\n\t"
"bnez t0, WhileLoop\n\t"
"addi %[add_cnt], %[add_cnt], 1\n\t"
"addi %[log], t1, -1\n\t"

