"addi %[add_cnt], %[add_cnt], 1\n\t"
"addi t1, x0, 0\n\t"
"addi %[add_cnt], %[add_cnt], 1\n\t"
"addi t2, x0, 1\n\t"
"addi %[fsub_cnt], %[fsub_cnt], 1\n\t"
"fsub.s %[pi], %[pi], %[pi]\n\t"
"PI_LOOP:\n\t"
"addi %[others_cnt], %[others_cnt], 1\n\t"
"bge t1, %[N], PI_END\n\t"
"addi %[others_cnt], %[others_cnt], 1\n\t"
"slli t3, t1, 1\n\t"
"addi %[add_cnt], %[add_cnt], 1\n\t"
"addi t3, t3, 1\n\t"
"addi %[others_cnt], %[others_cnt], 1\n\t"
"fcvt.s.w f1, t2\n\t"
"addi %[others_cnt], %[others_cnt], 1\n\t"
"fcvt.s.w f2, t3\n\t"
"addi %[fdiv_cnt], %[fdiv_cnt], 1\n\t"
"fdiv.s f2, f1, f2\n\t"
"addi %[others_cnt], %[others_cnt], 1\n\t"
"andi t4, t1, 1\n\t"
"addi %[others_cnt], %[others_cnt], 1\n\t"
"bne t4, x0, ODD\n\t"
"addi %[fadd_cnt], %[fadd_cnt], 1\n\t"
"fadd.s %[pi], %[pi], f2\n\t"
"addi %[others_cnt], %[others_cnt], 1\n\t"
"beq x0, x0, PI_NEXT\n\t"
"ODD:\n\t"
"addi %[fsub_cnt], %[fsub_cnt], 1\n\t"
"fsub.s %[pi], %[pi], f2\n\t"
"PI_NEXT:\n\t"
"addi %[add_cnt], %[add_cnt], 1\n\t"
"addi t1, t1, 1\n\t"
"addi %[others_cnt], %[others_cnt], 1\n\t"
"beq x0, x0, PI_LOOP\n\t"
"PI_END:\n\t"
